version: '3'
services:
  dice-openresty:
    container_name: dice-openresty
    build:
      context: ./
      dockerfile: ./dice-docker/dice-openresty/openresty-Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
    - "80:80"
    volumes:
    - ~/.dice/logs/openresty:/usr/local/openresty/nginx/logs
    depends_on:
    - dice-server
    - dice-front
    networks:
      dice-net:
        ipv4_address: 172.28.1.1

  dice-mysql:
    container_name: dice-mysql
    build:
      context: ./
      dockerfile: ./dice-docker/dice-mysql/dice-mysql-Dockerfile
    environment:
      MYSQL_DATABASE: dice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    expose:
    - "3306"
    volumes:
    - ~/.dice/mysql/mysql_data:/var/lib/mysql
    restart: always
    networks:
      dice-net:
        ipv4_address: 172.28.1.2

  dice-server:
    container_name: dice-server
    build:
      context: ./
      dockerfile: ./dice-docker/dice-server-Dockerfile
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
    volumes:
    - ./dice-server:/app
    - ~/.m2:/root/.m2
    - ~/.dice/logs/server:/app/log
    - ~/.dice/upload:/root/.dice/upload
    expose:
    - "9091"
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker -Dmaven.test.skip=true
    depends_on:
    - dice-mysql
    - dice-redis
    restart: always
    networks:
      dice-net:
        ipv4_address: 172.28.1.3

  dice-redis:
    container_name: dice-redis
    build:
      context: ./
      dockerfile: ./dice-docker/dice-redis-Dockerfile
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      dice-net:
        ipv4_address: 172.28.1.4

  dice-front:
    container_name: dice-front
    build:
      context: ./
      dockerfile: ./dice-docker/dice-front-Dockerfile
    environment:
      TZ: Asia/Shanghai
    expose:
    - "3000"
    depends_on:
    - dice-server
    networks:
      dice-net:
        ipv4_address: 172.28.1.6

networks:
  dice-net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16
